### ISSUE TITLE
Entire Docs site is 404 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#1341]
When I go to to any page on the docs site docs.communityhealthtoolkit.org I get a `404`:

![image](https://github.com/medic/cht-docs/assets/8253488/acab7bba-6495-4e5b-b1f6-77c4e13893a8)

**Comment by mrjones-plip** [comment]
issue has been resolved - docs site got overwritten accidentally by the tech radar content via misconfiguration CI.  Fix was to re-run the most [recent action](https://github.com/medic/cht-docs/actions) that published the docs site.

Leaving this ticket open to document exact steps that led to the issue. per @andrablaj 

> The problem was that t[his change](https://github.com/medic/cht-tech-radar-contributors/commit/5278f9e384977a72198c034118f207e041a63313) on Tech Radar triggered a GH action which then replaced the content on the [docs site](https://github.com/medic/medic.github.io/commits/main/).

**Comment by andrablaj** [comment]
Per the discussion in [this ticket](https://github.com/medic/cht-tech-radar-contributors/issues/3), the CI on Tech Radar does not deploy automatically all the new changes to GitHub Pages, because the CI on that repo doesn't have the right to write to GH Pages. 

I requested the creation of a secret to follow the steps explained [used by cht-docs CI to deploy to GH Pages](https://github.com/medic/cht-tech-radar-contributors/issues/3#issuecomment-1903359711), and also [this tutorial ](https://www.kevinhooke.com/2022/11/10/gp-pages-deploy-fails-when-run-from-github-action-author-identity-unknown/) that explains how to tackle the error I was getting.

After [setting up the secret](https://github.com/medic/cht-tech-radar-contributors/commit/74dd974a1e941185252434c8589e2e4511d081e1), the content on [medic.github.io](https://github.com/medic/medic.github.io)  was replaced with Tech Radar content completely, which can be see in the [commit history](https://github.com/medic/medic.github.io/commits/main/), more particularly [this change](https://github.com/medic/cht-tech-radar-contributors/commit/74dd974a1e941185252434c8589e2e4511d081e1). 

This was reverted by re-running the latest GH action on `cht-docs`.

The `DEPLOY_TO_GITHUB_PAGES` was deleted by @craig-landry.
