### ISSUE TITLE
'Page_Feedback' disappeared after hugo and docsy upgrade

### ISSUE THREAD

**Issue by esthermmoturi** [medic/cht-docs#1450]
After Upgrading docsy to version 0.10.0 from 0.7.0 and upgrading hugo to hugo v0.126.3+extended darwin/arm64, the page feedback element disappeared. I have attached images with the issue I am experiencing. [Here](https://github.com/medic/cht-docs/tree/upgrade-hugo-and-docsy) is the branch that contains the upgraded code.

Steps taken in troubleshooting:

- [ ] Reviewed docsy and hugo discussion platforms for people who have experienced the same issue - found none
- [ ] Raised [question](https://github.com/google/docsy/discussions/2052) on Docsy discussion platform - Unanswered
- [ ] Replicated issue in mobile and desktop view
- [ ] Viewed docsy [release notes](https://github.com/google/docsy/blob/main/CHANGELOG.md) - changes on page feedback happened in v0.8.0

**Comment by esthermmoturi** [comment]
Hey @alexrashed have you experienced this issue?

**Comment by alexrashed** [comment]
No, not really, sorry, but after having a quick look, I would guess that this might be caused by the upstream docsy default layout has changed and yours has not been adjusted yet?
[Yours](https://github.com/medic/cht-docs/blob/b929ce075ae4df552989747590e36c85a2fac465/layouts/_default/content.html) VS [Upstream](https://github.com/google/docsy/blob/309da207e5deeda762348bfd0cc32367c5565a1e/layouts/_default/content.html)

**Comment by esthermmoturi** [comment]
That could be it actually, I have noticed that if I change the file one of my pages has the 'Page_feedback', curious why it's not rendering for all pages.

**Comment by esthermmoturi** [comment]
Closing this as the _'content.html'_ file and _'list.html'_ file were fixed.
