### ISSUE TITLE
Deployment team feedback on new documentation site

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#153]
Deployment team members are primary users of the new documentation site. It would be helpful to gain feedback from a few team members who were not engaged in the initial build out of the site to understand potential areas for further improvement. Some of the areas that we would like specific feedback: 

- site navigation (ie finding the information you are looking for)
- contributing and requesting changes to pages
- [quick guides](https://docs.communityhealthtoolkit.org/apps/guides/)
- [reference section](https://docs.communityhealthtoolkit.org/apps/reference/)
- questions or needs that projects partners often request information for that are not addressed currently (or sub-optimally addressed) in the current site
- things we can do to make it easier to get started
- other general feedback

**Comment by MaxDiz** [comment]
Hi @rosteve @marina-kenf @binokaryg would you be willing to provide feedback on the [new documentation site](https://docs.communityhealthtoolkit.org/)? Happy to setup calls or feel free to add to this ticket.

**Comment by Marina-Kenf** [comment]
@MaxDiz  yes, I'll be happy to provide this! From the first view, the site looks very smart! My feedback as per your specification will follow very soon.

**Comment by rosteve** [comment]
@MaxDiz , I'm more than happy to provide my feedback! It looks great! The site navigation and the documentation structure is great as well. I'd prefer we set a call so that we can interactively discuss

**Comment by binokaryg** [comment]
@MaxDiz, the new documentation site looks great.
Here is my feedback after first look:

**1. Site Navigation:**
I liked how the topics are organized and related topics are listed in the end. When I searched for "targets", here is the order of search results I got:

> i. What's new in the Core Framework: 3.8.0 | Medic Mobile (Medic Mobile blog)
> ii. Topics tagged targets (CHT Forum)
> iii. Clarification on Target documents in CouchDB - Technical Support ... (CHT Forum)
> iv. Targets | Community Health Toolkit (CHT Docs)

I expected the 4th result to appear on the top. Can we configure it so that the results within the same site appear first?

**2. Contributing**
When I click on "Edit this page", I am taken to Github directly. Can we add an intermediate page here (for first-timers at-least) that talks in brief about forking, editing, and also link to the [Style Guide](https://docs.communityhealthtoolkit.org/docs-style-guide/)?

**3. Quick guides**
Is there a specific order for the topics/categories?
Can we add some icons so that we can quickly find the ones that we are looking for?

**4. Reference section**
I liked how it is structured similarly to the config structure of our projects.

I think that this new documentation will be very helpful to the deployment team members and external users too.

**Comment by Marina-Kenf** [comment]
@MaxDiz please see below my feedback. 

• **Site navigation (ie finding the information you are looking for)**
Finding results are sometimes pointing out of the site, even for the first results, for example the search of “quick guides”. Maybe we could restraint this result in the site then add at the bottom the option to search on Google. 

• **Contributing and requesting changes to pages**: OK

• **Quick guides and reference section**
If the links of this sections were not precised in your feedback request message, maybe it would not have been obvious to find it, unless reading the CHT Application overview first. I suggest adding an arrow  near each title on the left menu to indicate that there is a navigation hierarchy.

In general, the site is easy very friendly and the descriptions are done with much details. That is great!

**Comment by MaxDiz** [comment]
Thanks @rosteve for the feedback. Notes from our discussion:  

* Search organization is confusing- start with results from doc site ([relevant slack discussion](https://medic.slack.com/archives/CUXB9SVT5/p1592431801125800))

* Navigation display could be cleaner by using a different highlight color, hierarchy dividers, and/or sub-drop-down menus 

<img width="256" alt="image1" src="https://user-images.githubusercontent.com/46463417/85744745-bdab7180-b6ca-11ea-93b3-a51a29382acd.png">

* Graphic of where CHT fits within the ecosystem would be helpful in communicating to new/potential partners

* A few dead links identified (Osoro to create GH issue)

* CHT Application - Reference - move Reference up a level in the hierarchy (ie put in primary navigation) to make it easier for app developers to find info

**Comment by MaxDiz** [comment]
Thanks again @binokaryg @Marina-Kenf and @rosteve for the feedback! I will review your suggestions with squad members and create follow-up issues for improvements where needed.
