### ISSUE TITLE
PNC example implementation documentation

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-docs#156]
Postnatal care is a workflow deployed across 90%+ of CHT projects. We should provide a detailed [example](https://docs.communityhealthtoolkit.org/apps/examples/) on the documentation site for implementing partner reference. Proposed structure of the documentation:

- intro
- problem being addressed
- solution overview
- user roles
- reporting hierarchy 
- care / app workflow 
- impact metrics (or reference to related documentation)

cc: @helizabetholsen

**Comment by MaxDiz** [comment]
relevant presentation: https://docs.google.com/presentation/d/1P4rlt7ve3TaYCDHXqeoxDiAtMwO6QQXmon5YfUH4ZBM/edit#slide=id.p3

**Comment by helizabetholsen** [comment]
relevant impact logic: https://docs.google.com/document/d/177AOhl6UngR28gpTqHJyGi2Mfo4TInCgxU9odk61TZ8/edit

relevant metrics: https://docs.google.com/spreadsheets/u/1/d/1rkPyZ34NVDWmbSRlzyriKzu4tFO8JP86vVUYSsGnIkA/edit#gid=1372327938

**Comment by helizabetholsen** [comment]
**Introduction**
Maternal health is the cornerstone of many community health programs. Pregnancy can be a vulnerable time for women living in communities far from medical care. Additionally, the short window immediately after pregnancy is a critical time for catching life-threatening danger signs for the new mother and baby. Digital tools, such as the Community Health Toolkit, can help better provide essential postnatal care to mothers and babies. 

**Problem Being Addressed**
Addressing the combined burden of maternal and newborn mortality in low and middle-income countries (LMICs) is a global priority, as well as a key component of achieving the Sustainable Development Goals (SDGs).  Nearly 75% of neonatal and maternal deaths occur in the first week of life, with up to half in the first 24 hours following delivery (Lawn et al. 2009; WHO). Antenatal and postnatal care (ANC/PNC) within a continuum is recognized to have the greatest impact on maternal and newborn survival. However, most mothers and newborns in LMICs countries often do not receive optimal care post-delivery for a variety of reasons, including access to care and gaps in follow-up.

**Solution Overview**
_Need input from the Service Design team_

Our maternal health solutions encompass a holistic set of use cases that include family planning, antenatal care, and postnatal care. 

The PNC workflow seeks to address issues pertaining to the mother and the baby immediately following birth and up to 6 weeks (42 days) afterwards. Early and timely postnatal care visits improve the wellbeing of mothers and babies and increase maternal and newborn survival by referring to advanced care when it is needed.

CHWs use the CHT to:
- Provide doorstep PNC visits and newborn assessments
- Guide families through PNC care
- Screen for danger signs in mothers and newborns
- Refer to the facility when necessary
- Follow-up on missed visits 

Facility staff use the CHT to:
- Provide facility PNC visits
- Track visit attendance
- Ensure healthy families and communities thrive

**User Roles**

_CHWs_
As a CHW, I would like to receive a reminder when I need to visit a new mother to check in on her postnatal status and her baby so that I provide timely services and ensure healthy outcomes.
As a CHW, I would like the ability to report on missed PNC visits and provide a reason, so that my supervisors are aware of the services that I am providing and understand various challenging external factors I cannot control, and can do their part to develop ways to counter such external factors. 

_Nurses & Clinic Staff_
As Nurse Mary, I would like the CHWs under my health facility to report on PNC visits so that I can ensure that all mothers are receiving the recommended care. As CHWs are checking in with the mothers to ask about their PNC visits, I can be sure that if they have missed to visit the health facility for some reason, they are at least being checked in by the CHWs. 

**Reporting Hierarchy**

_Need input from service design team, likely similar to PHC monitoring content_

**Workflow Diagram**

_See linked deck above_

**Impact Metrics**

There are a few key impact metrics that we use to track activity and impact across deployment of the CHT that include the PNC workflow. These are intended for cross-project learnings across model-building partners, informing product feature updates, and other research purposes. Our priority impact metrics seek to assess both CHW activity, as well as the overall access and coverage of PNC services in the communities they serve.

These metrics include:
- number of CHWs participated in PNC
- number of PNC enrollments
- number of confirmed PNC visits
- proportion of deliveries confirmed of expected
- proportion of women receiving their first PNC visit within 48 hours of delivery
- proportion of women receiving 3+ PNC visits during the PNC period 

For more information, please refer to our Impact Metrics & Monitoring documentation.

**Comment by MaxDiz** [comment]
Closing this issue via #167 , which transitioned the `ANC reference app` documentation to now be the `Maternal and Newborn Health Reference App`. 

@helizabetholsen what do you think about adding a combined (ANC + PNC) Impact Metrics section to the [new page](https://docs.communityhealthtoolkit.org/apps/examples/anc/)? Please open a new issue if you think it would be worthwhile.
