### ISSUE TITLE
Google search in docs returns stale results/404s

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#197]
Searching for [introduction](https://docs.communityhealthtoolkit.org/search/?q=introduction#gsc.tab=0&gsc.q=introduction&gsc.ref=more%3Adocumentation&gsc.sort=) or community health toolkit brings results that includes this broken link - (see the screenshot below)`https://docs.communityhealthtoolkit.org/docs/application_development/guides/from_scratch/001_introduction.html`
[![Screen Shot 2020-06-26 at 12 42 47 PM](https://user-images.githubusercontent.com/6769401/85844262-1ce0b300-b7ab-11ea-8a0b-2413f7661764.png)](url)

A more specific example is to search for [001_introduction.html](https://docs.communityhealthtoolkit.org/search/?q=001_introduction.html#gsc.tab=0&gsc.q=001_introduction.html&gsc.page=1) which as of now (Jun 30 2020) shows a single result which has been in there for 5+ days and 404s.

There should be a way to keep the search results more up to date maybe?

(adopted from #184)

**Comment by mrjones-plip** [comment]
@rosteve - FYI

**Comment by mrjones-plip** [comment]
@abbyad  - FYI it looks like we deleted the top level `docs` directory on May 30th which means the results are 30+ days old. See f1a8aeeda651970ced5040724f6566d3bbe7c3d8 for the specifics.  (as an aside, is there anything git can't do!?! I used `git log --diff-filter=D --summary .|less` to hunt down when this top level dir was deleted).

**Comment by abbyad** [comment]
I think as part of this issue we should also improve our 404 page. It currently says `Oops! This page doesn't exist. Try going back to our home page.` 
![image](https://user-images.githubusercontent.com/789512/86608970-3935da00-bf79-11ea-84b7-4d5954bf0afd.png)

We should give the option to search directly from it, and acknowledge in some way that the 404 is most likely our fault due to moving content as part of the re-launch. For example: 
`Sorry! This page doesn't exist. We've made big changes to our documentation lately and some pages have moved around. Try the search box to find the content you are looking for.`

Also, since I first looked at the search in question, the search itself has now been added as a search result 🤦 

## before
![image](https://user-images.githubusercontent.com/789512/86608813-07247800-bf79-11ea-9d2a-e8fd660eb2bc.png)

## after
![image](https://user-images.githubusercontent.com/789512/86608670-d93f3380-bf78-11ea-9dd1-b6efdb73813b.png)

**Comment by mrjones-plip** [comment]
@abbyad  - d'oh!  Maybe we can exclude `/search` from the search results?  

I'd say we have two tickets then:

1. Remove stale results from search (this ticket).  Could also be "keep search results fresh over the long term"
1. Improve 404 page (a new ticket)

However, what ever is clever - I don't need to be pedantic about how we improve things!

**Comment by abbyad** [comment]
While working on #211 I've excluded /search from the GCSE results.

**Comment by abbyad** [comment]
I have put all folders of the previous website in the "exclude" list for our google search so that they get removed immediately. (`atp` is a GH project page that we have, but don't want to search for)

![image](https://user-images.githubusercontent.com/789512/87079084-8cb35c80-c1f3-11ea-8176-aa685c4a145e.png)

Individual stale results can be removed using this public Google site: https://www.google.com/webmasters/tools/removals

Closing this issue as the stale results are no longer accessible in our search. @mrjones-plip please feel free to open new issue if you notice any more problems. Note that other search improvements are coming with #211!

**Comment by mrjones-plip** [comment]
Looking really good - thanks!  No more 404s, no regressions.  Once we get #211 done, we'll be in tip top search shape I think!

FYI @rosteve
