### ISSUE TITLE
After deploying blank project, Error message(400 error) is showing up upon clicking on add New Health facility 

### ISSUE THREAD

**Issue by bindugowrig** [medic/cht-docs#357]
**Steps to reproduce:**
1.Follow the steps in [local setup](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/)
2.Install medic-conf
3.Install the core framework
4.Open https://localhost on a Google Chrome browser 
5.Login with username **medic** and default password **password**
6.Click on People tab and click on  + New Heath Facility
7.Observe New health facility form is showing up
8.Create New blank project (mkdir cht-app-tutorials, cd cht-app-tutorials, medic-conf initialise-project-layout)
9.Deploy blank project on local test environment(medic-conf --url=https://medic:password@localhost --accept-self-signed-certs)
10.Go to Google Chrome browser
11.Refresh the page
12.Observe "Error loading form.Please try again or check with an administrator" message is showing up.

![Add new health facility-404  error](https://user-images.githubusercontent.com/73226533/97425340-00f74480-1938-11eb-911f-aea37322eb82.png)

**Fix/Alternative Provided:**
1.Copy and past the contacts(Create) from [contacts](https://github.com/medic/cht-core/tree/master/config/default/forms/contact) in the forms/contact  subfolder of your project folder.
2.From within the project folder, run the command 
medic-conf --url=https://<username>:<password>@localhost --accept-self-signed-certs upload-contact-forms
3.Forms uploaded successfully.
4.Refresh the page in Google chrome browser.
5.Click on +New Health Facility and observe New Health facility form is showing up.

**Comment by garethbowen** [comment]
When you run `medic-conf` in step 9, one of the stages is to delete-all-forms which does exactly what it sounds like - deletes all the forms on localhost. Then we upload all the forms in the local configuration, which because it's a blank project has no forms at all. This is why the "Error loading form" is shown.

Your fix will work, but you will find other forms or configurations are missing. I recommend you copy the entire `config/default` directory to your local config directory and then modify it as needed.

**Comment by garethbowen** [comment]
Closing as solved. Please reopen, or even better, post to the [CHT forum](https://forum.communityhealthtoolkit.org/) if you have any other questions.
