### ISSUE TITLE
Set default repo to `main` for docs publishing repo

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#636]
For the [repo where the docs site is served from](https://github.com/medic/medic.github.io), we should switch the default repo from `master` -> `main`.  Opening this ticket in case there was a reason to not have switched it already when the `main` branch was created.

CC @dianabarsan @jonathanvq @latin-panda

**Comment by jonathanvq** [comment]
@mrjones-plip I have updated the repository, and now 'main' is the default branch.  I think it was broken since I pushed [this](https://github.com/medic/cht-docs/commit/f85b2e471229081b31f0c0eafdeb5c1de7286316) change in cht-docs repo:

![image](https://user-images.githubusercontent.com/28880764/153673665-15c6e803-2c2d-413b-8284-ca2113da79a2.png)

If I'm not wrong, it was pushing to the main branch in the repo for GH pages, but the master branch was the one being read to publish to the website. I apologize for causing this issue.

I think at this point it is also safe to delete the master branch in https://github.com/medic/medic.github.io, but please let me know if you think of something else that I should consider before proceding.

Thanks!

c.c. @dianabarsan | @latin-panda

**Comment by mrjones-plip** [comment]
Thanks for the switch on the default.  I think it's safe to delete the `master` branch too on `medic.github.io` repo, but don't know what standard practice is on other repose that we've switched over too.  Do we delete on all them?  It would be cleaner to delete!

**Comment by jonathanvq** [comment]
Yes, we do delete them. I'll do it and then close this issue. Thanks
