### ISSUE TITLE
Broken links (404)

### ISSUE THREAD

**Issue by jonathanvq** [medic/cht-docs#643]
@garethbowen, @abbyad, while I was working on https://github.com/medic/cht-docs/pull/616, I found a few broken links which I couldn't fix as I don't know where they should link to.

Some of these seem to be references to quite old versions of the CHT.

Here are the links:

| URL where the link is present | Evidence |
| ------------- | ------------- |
| https://docs.communityhealthtoolkit.org/apps/reference/forms/app/  | ![image](https://user-images.githubusercontent.com/28880764/155226982-4a43b962-2a62-4510-9870-d932c95ea1bd.png) |
| https://docs.communityhealthtoolkit.org/core/releases/2.15.0/   | ![image](https://user-images.githubusercontent.com/28880764/155227118-68d5663a-7666-43ae-bda2-a83dcc5a6992.png)  |
| https://docs.communityhealthtoolkit.org/apps/reference/contact-page/  | ![image](https://user-images.githubusercontent.com/28880764/155227968-f3cb3ba4-dbf9-44e0-8650-948c6757e305.png)  |
| https://docs.communityhealthtoolkit.org/core/releases/2.13.0/  | ![image](https://user-images.githubusercontent.com/28880764/155228155-6d6c75d7-af81-4cb3-a3ef-6ef3421b01b4.png)  |
| https://docs.communityhealthtoolkit.org/core/releases/3.4.0/ | ![image](https://user-images.githubusercontent.com/28880764/155228265-ec5cf6a4-4f57-4454-af0c-9763d215ce4b.png) |
| https://docs.communityhealthtoolkit.org/core/releases/3.2.0/ | ![image](https://user-images.githubusercontent.com/28880764/155228437-afb2a433-ec7f-4646-aca7-30ac681fb92e.png) |

Can you please take a look and suggest how to fix these?

Thanks.

**Comment by garethbowen** [comment]
1. This resource has been moved to a private repo ( https://github.com/medic/support-scripts/blob/master/forms/z-score.xml ) because it's not officially supported or tested. It'd be better to grab the relevant bits out of it and inline it into this doc rather than linking.
2. It's probably meant to link here: https://github.com/medic/cht-core/blob/master/config/standard/app_settings.json - maybe link to a specific commit (rather than master) so it's immutable.
3. There's a very similar field in the section above on this page which now points to https://github.com/medic/cht-core/tree/3.11.x/webapp/src/ts/pipes - probably use this one.
4. There's a similar link in the point below and I think they should both point to the same place: https://docs.communityhealthtoolkit.org/apps/reference/contact-page/#contact-summary
5. Not sure, but maybe https://docs.communityhealthtoolkit.org/apps/reference/resources/#branding 
6. Not sure, but maybe https://docs.communityhealthtoolkit.org/apps/reference/app-settings/transitions/#muting

@abbyad Do you know where the feature overview PDFs (5 & 6) ended up?

**Comment by abbyad** [comment]
I don't see the content well represented in the docs site. For reference, these are the docs in question:
5. [Branding Guide](https://github.com/medic/medic-docs/blob/4dcf112bd652d463603d9c4f5287264dba985443/features/webapp-branding.pdf)
6. [Muting Overview](https://github.com/medic/medic-docs/blob/3afbfca835a2836b2ce27f589f2613ccc368b2fc/features/muting-overview.pdf)

We could create doc site guides with this content, but for now probably simplest to bring these PDFs into an accessible place.

**Comment by esthermmoturi** [comment]
1 - 3 . All broken links have been fixed 
4. Done
5.  [Branding guide](https://docs.communityhealthtoolkit.org/building/tutorials/application-graphics/) placed on the doc site
6. [Muting Overview](https://docs.communityhealthtoolkit.org/building/workflows/muting/) on the doc site.
