### ISSUE TITLE
relatedContent on CHT Applications ->Features -> * not showing

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-docs#758]
In this [targets page](https://docs.communityhealthtoolkit.org/apps/features/targets/) the code has some related content defined in the markdown (see below). However, the related content does not show at the bottom of the page. This is true for all the pages in 
`content/en/apps/features/*` but not for the sub-directory `/apps/features/integrations/*`.

Affected pages:

 * [Contacts](https://docs.communityhealthtoolkit.org/apps/features/contacts/)
 * [Messaging](https://docs.communityhealthtoolkit.org/apps/features/messaging/)
 * [Reports](https://docs.communityhealthtoolkit.org/apps/features/reports/)
 * [Supervision](https://docs.communityhealthtoolkit.org/apps/features/supervision/)
 * [Tasks](https://docs.communityhealthtoolkit.org/apps/features/tasks/)
 * [Targets](https://docs.communityhealthtoolkit.org/apps/features/targets/)
 * [UHC Mode](https://docs.communityhealthtoolkit.org/apps/features/uhc-mode/)
 * [App Management](https://docs.communityhealthtoolkit.org/apps/features/admin/)
 
```
---
title: Targets
weight: 8
description: >
  Dashboards to track metrics for an individual CHW or for an entire health facility
keyword: targets
relatedContent: >
  apps/reference/targets
  core/overview/db-schema#targets
  apps/features/integrations/dhis2
  apps/features/supervision/#chw-aggregate-targets
---
<!-- ## Targets: Performance Dashboards -->

*Targets* is the user dashboard or analytics tab. The widgets on this tab provide a summary or analysis of the data in submitted reports. These widgets can be configured to track metrics for an individual CHW, for a Supervisor overseeing a group of CHWs, or for an entire health facility. 
```

**Comment by mrjones-plip** [comment]
I tried replacing the code for code for the targets page with known good content that did show the related content - this didn't fix it :thinking:

**Comment by mrjones-plip** [comment]
@jkuester  - pinging you in case some of the [hugo uplift work](https://github.com/medic/cht-docs/pull/731) you corrected this already on some other pages and know an easy fix!  (but **_not_** because you are now the "fixes all the docs bugs" person :laughing: )

**Comment by jkuester** [comment]
Hmm this is very strange!  For context, the "Related Content" is custom logic that we have [added to our layout](https://github.com/medic/cht-docs/blob/6e2926dac8138b5007eadea712f66dca738fee9d/layouts/_default/content.html#L14).  I would guess you are correct that something in the Hugo uplift caused this to break (though it is surprising to me that it broke for some pages and not others....).  I will try and do some more digging on this to figure out what the root cause is...

(On a somewhat related note, what do you think of Hugo/Docsy's [taxonomy system](https://www.docsy.dev/docs/adding-content/taxonomy/)? Seems to provide similar value to users while being more flexible (and not a roll-your-own solution...).)
