### ISSUE TITLE
Fix source of text on task

### ISSUE THREAD

**Issue by abbyad** [medic/cht-docs#827]
Page: [/design/best-practices/](https://docs.communityhealthtoolkit.org/design/best-practices/#anatomy-of-a-task)
Version: 2021-07-16 08:15:33 -0500 -0500
---

The second line in a task is specified both as the form title (incorrect), and the task name (correct). We should update for accuracy.

![image](https://user-images.githubusercontent.com/789512/200682540-19061421-cdd4-44c3-b043-2163f68f798a.png)

**Comment by tmatheas** [comment]
Hi @abbyad , Can you please assign this issue to me. Also can you please add the `hacktoberfest` tag to this issue.

**Comment by tmatheas** [comment]
@andrablaj Can you explain the issue a little bit ?

**Comment by andrablaj** [comment]
@latin-panda do you think you can support @tmatheas with his question? I assume this is just about updating the highlighted line to match what the actual second line is about?

**Comment by latin-panda** [comment]
@tmatheas Thanks for picking this up! 

[This page](https://docs.communityhealthtoolkit.org/design/best-practices/)'s image is showing wrong information 

To avoid confusion is better to say "task" instead of "form", and say "title" instead of "name" since it aligns better to the terms of task configuration

<img width="800" alt="Screenshot 2024-10-01 at 4 07 20 PM" src="https://github.com/user-attachments/assets/f152a225-56b8-4eff-b389-02e133d64173">

 <br> <br>

In [this other page](https://docs.communityhealthtoolkit.org/building/reference/tasks/), we already have another image that seems to use better terms. I think you can use it:  
<img width="800" alt="Screenshot 2024-10-01 at 4 14 03 PM" src="https://github.com/user-attachments/assets/285d92c4-13af-48cb-82ff-1ae67fa847b2">

**Comment by tmatheas** [comment]
@latin-panda I have made the changes. Can you check this is fine ?
<img width="892" alt="image" src="https://github.com/user-attachments/assets/44608c8c-3e7c-4b4d-bb26-7b722b4030f2">

**Comment by latin-panda** [comment]
@tmatheas That looks good! Once [you open a pull request](https://docs.communityhealthtoolkit.org/contribute/code/workflow/#pull-requests) to the `main` branch, feel free to add me as a reviewer

**Comment by tmatheas** [comment]
#1580 Linking the PR

**Comment by tmatheas** [comment]
[https://github.com/medic/cht-docs/pull/1581](url)

**Comment by tmatheas** [comment]
@latin-panda #1581 Here is the PR

**Comment by latin-panda** [comment]
@tmatheas thank you for submitting this contribution! It has been incorporated into CHT Docs!

**Comment by tmatheas** [comment]
@latin-panda Can you add `hacktoberfest-accepted` tag to the issue also
